### ISSUE TITLE
Getting unauthorized message after running application for some time.

### ISSUE THREAD

**Issue by mathiasbl** [microsoft/PowerPlatform-DataverseServiceClient#102]
After my application was running about 1 hour (I assume) every subsequential request started failing with message:
The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Bearer authorization_uri=xx, resource_id=xx'.

The client was running fine before this.

Version:0.3.6-Alpha

I pool cloned CdsServiceClients. Do they also manage token refresh?
Worth mentioning that I'm falling back to the SOAP service. (see code below)

```
client.ExecuteCdsOrganizationRequest(request, useWebAPI: false);
```

Stacktrace:
 MessageSecurityException - Create : User Defined |=> The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Bearer authorization_uri=xx, resource_id=xx'.
Source: System.Private.ServiceModel
Method: ValidateAuthentication
DateUTC: 2/26/2021
TimeUTC: 8:03:10 PM
Error: The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Bearer authorization_uri=xx, resource_id=xx'.
HelpLink Url: Not Provided
Stack Trace: at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateAuthentication()
   at System.ServiceModel.Channels.HttpResponseMessageHelper.ParseIncomingResponse(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.ReceiveReplyAsync(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.RequestAsyncInternal(Message message, TimeSpan timeout)
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
   at generatedProxy_1.Execute(OrganizationRequest )
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClient.<>c__DisplayClass40_0.<ExecuteCore>b__0()
   at Microsoft.Xrm.Sdk.WebServiceClient.WebProxyClient`1.ExecuteAction[TResult](Func`1 action)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClient.ExecuteCore(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClient.Execute(OrganizationRequest request)
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.CdsCommand_Execute(OrganizationRequest req, String errorStringCheck, Boolean bypassPluginExecution)

**Comment by MattB-msft** [comment]
Yes, there is token management based on MSAL, the clones should be able to manage that as well, it applies regardless of SOAP or WebAPI pipes. 

We are still working on issues with token management in MSAL and are currently relying on in memory tokens. 

Your creating a pool of Clients from one that is setup as a Secret auth or cert Auth?  Are you constantly running or are there long periods of down time then you wake up and do work? 

thanks
MattB

**Comment by mathiasbl** [comment]
Using Secret Auth and the client had no downtime.

It's a data migration tool and was in progress moving a large data set.

**Comment by mathiasbl** [comment]
I've been trying to reproduce using a simple console app with multi threading and cloning. No luck so far.

**Comment by MattB-msft** [comment]
for your tool,, are you in a console app/ ux app / web App or function? 
also what OS?

**Comment by mathiasbl** [comment]
It was running a function on a windows premium plan (EP1).

**Comment by mathiasbl** [comment]
@MattB-msft I did some more testing and it looks like cloned clients don't seem to refresh their token after more than 1 hour of idle time. Hency why I am having the problem since I pool these clients.

The initial client, that spawned the clones, however still works after 1 hour and refreshes the token properly.

**Comment by MattB-msft** [comment]
We are looking into it.  
thanks for the report!
