### ISSUE TITLE
NullReferenceException when logging HttpOperationException

### ISSUE THREAD

**Issue by pareszka** [microsoft/PowerPlatform-DataverseServiceClient#111]
From time to time, in my org's test environment, there are NullReferenceExceptions coming from CdsServiceClient/ServiceClient, with a stack trace like this:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.LogException(OrganizationRequest req, Exception ex, String errorStringCheck, String webUriMessageReq)
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.CdsCommand_WebExecuteAsync(String queryString, String body, HttpMethod method, Dictionary2 customHeaders, String contentType, String errorStringCheck, Guid requestTrackingId)
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.CdsCommand_WebAPIProcess_ExecuteAsync(OrganizationRequest req, String logMessageTag, Boolean bypassPluginExecution, CancellationToken cancellationToken)
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.ExecuteCdsOrganizationRequestAsyncImpl(OrganizationRequest req, CancellationToken cancellationToken, String logMessageTag, Boolean useWebAPI, Boolean bypassPluginExecution)
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.CreateAsync(Entity entity, CancellationToken cancellationToken)`

We are currently using version 0.3.10-Alpha, but by checking last commits, it doesn't looks like it was recently fix.
By checking LogException method implementation, it looks for me, that in httpOperationException.Response.Content can be sometimes null.

**Comment by MattB-msft** [comment]
This was fixed in current releases,, Please update and let us know if your still seeing it.

**Comment by MattB-msft** [comment]
Closing as no feedback.. please reopen if your still seeing the issue.
