### ISSUE TITLE
Error reading JObject from JsonReader when logging exception

### ISSUE THREAD

**Issue by pareszka** [microsoft/PowerPlatform-DataverseServiceClient#137]
I've encountered an exception coming from the newest (0.4.12) Dataverse lib, when one of the requests failed. This is the stack trace:
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.LogException(OrganizationRequest req, Exception ex, String errorStringCheck, String webUriMessageReq)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.Command_WebExecuteAsync(String queryString, String body, HttpMethod method, Dictionary`2 customHeaders, String contentType, String errorStringCheck, Guid requestTrackingId)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.Command_WebAPIProcess_ExecuteAsync(OrganizationRequest req, String logMessageTag, Boolean bypassPluginExecution, CancellationToken cancellationToken)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.ExecuteOrganizationRequestAsyncImpl(OrganizationRequest req, CancellationToken cancellationToken, String logMessageTag, Boolean useWebAPI, Boolean bypassPluginExecution)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.CreateAsync(Entity entity, CancellationToken cancellationToken)

If I checked correctly in the telemetry, the failed request was throttled and for some reason the HttpOperationException didn't have a correct content body

**Comment by svejdo1** [comment]
For clarity sake - this is retrieval of cosmos-backed entity. This might be helpful: 
WebRequestStatistics
| where PreciseTimeStamp   between (datetime(2021-05-31 20:00) .. 1d)
| where ClientSessionId == "5f8fea4c-92ee-4d0f-9bab-e90bac60a13f"

**Comment by MattB-msft** [comment]
Thanks, 
Checking into it now.

**Comment by MattB-msft** [comment]
We have identified this and are doing some refactoring of the error handers to catch this sort of situation.
