### ISSUE TITLE
System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')

### ISSUE THREAD

**Issue by ethax-ross** [microsoft/PowerPlatform-DataverseServiceClient#139]
I ran into this error after updating to the renamed client in v4 - its triggered when trying to log out another exception I've encountered since the upgrade (which appears to be caused by passing a `null` value to an option set when updating a contact record, though I haven't pinned it down fully yet).

```
Microsoft.Xrm.Sdk.SaveChangesException: An error occured while processing this request.
 ---> System.AggregateException: One or more errors occurred. (Length cannot be less than zero. (Parameter 'length'))
 ---> System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.PowerPlatform.Dataverse.Client.DataverseTraceLogger.GetFirstLineFromString(String textBlock)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.ShouldRetryWebAPI(Exception ex, Int32 retryCount, Boolean& isThrottlingRetry)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.Command_WebExecuteAsync(String queryString, String body, HttpMethod method, Dictionary`2 customHeaders, String contentType, String errorStringCheck, Guid requestTrackingId)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.Command_WebAPIProcess_ExecuteAsync(OrganizationRequest req, String logMessageTag, Boolean bypassPluginExecution, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.ExecuteOrganizationRequestImpl(OrganizationRequest req, String logMessageTag, Boolean useWebAPI, Boolean bypassPluginExecution)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.Execute(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.Execute(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.SaveChange(OrganizationRequest request, IList`1 results)
   --- End of inner exception stack trace ---
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.SaveChanges(SaveChangesOptions options)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.SaveChanges()
```

Somehow `Contains` is returning `true` but `IndexOf` must be returning `-1`, which is why we get the length less than zero error:

```
if (textBlock.Contains(Environment.NewLine))				
  return textBlock.Substring(0, textBlock.IndexOf(Environment.NewLine));
```

**Comment by MattB-msft** [comment]
We have not been able to get this failure to replicate.. 
however, we have decided to add a bit of paranoia code in to the logic path in order to help narrow down the issue. 
that will be included in the next drop we make publicly.
