### ISSUE TITLE
When creating a Contact record getting the following One or more errors occurred. (Object reference not set to an instance of an object.)

### ISSUE THREAD

**Issue by twiga2013** [microsoft/PowerPlatform-DataverseServiceClient#180]
Can someone please help me with the following error.

{"Object reference not set to an instance of an object."}
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2147467261
    HelpLink: null
    InnerException: null
    Message: "Object reference not set to an instance of an object."
    Source: "Microsoft.PowerPlatform.Dataverse.Client"
    StackTrace: "   at Microsoft.PowerPlatform.Dataverse.Client.Utilities.IsAttributeValidForOperation(AttributeMetadata attrib, HttpMethod requestedMethod)\r\n   at Microsoft.PowerPlatform.Dataverse.Client.Utilities.ToExpandoObject(Entity sourceEntity, MetadataUtility mUtil, HttpMethod requestedMethod, DataverseTraceLogger logger)\r\n   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.<Command_WebAPIProcess_ExecuteAsync>d__185.MoveNext()"
    TargetSite: {Boolean IsAttributeValidForOperation(Microsoft.Xrm.Sdk.Metadata.AttributeMetadata, System.Net.Http.HttpMethod)}

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.ExecuteOrganizationRequestImpl(OrganizationRequest req, String logMessageTag, Boolean useWebAPI, Boolean bypassPluginExecution)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.Create(Entity entity)
   at

**Comment by twiga2013** [comment]
Thank You!!
