### ISSUE TITLE
External Token Management and Organization name

### ISSUE THREAD

**Issue by bjorkstromm** [microsoft/PowerPlatform-DataverseServiceClient#214]
Hi!

I'm trying to use this client to connect to a Dynamics 365 on-prem instance. For "reasons" I'm also using `ExternalTokenManagement` as `AuthenticationType`. Somehow it seems that the organization name provided in the `instanceUrl` is omitted, which results in wrong URL for the Organization Service.

Example
```csharp
var uri = new Uri("https://mycompany.example.com/myorg/");
var client = new ServiceClient(uri, _ => Task.FromResult(token));
```

When inspecting using Fiddler I can see that the connection service is trying to access `https://mycompany.example.com/XRMServices/2011/Organization.svc` instead of `https://mycompany.example.com/myorg/XRMServices/2011/Organization.svc`, which results in a 401 (Unathorized) response. Trying to tweak the request manually, to make it go against `https://mycompany.example.com/myorg/XRMServices/2011/Organization.svc` instead results in a successful request.

Is it possible to have ServiceClient (and ConnectionService) not to omit the organization name when using external token management?

Logs
```
Initialize Dataverse connection Started - AuthType: ExternalTokenManagement
Direct Login Process Started
Attempting to Connect to Uri https://mycompany.example.com/XRMServices/2011/Organization.svc
BuildOrgConnectUri CoreClass ()
DiscoveryServer indicated organization service location = https://mycompany.example.com/XRMServices/2011/Organization.svc
BuildOrgConnectUri CoreClass ()
Organization Service URI is 'https://mycompany.example.com/XRMServices/2011/Organization.svc'
ConnectAndInitService - Initializing Organization Service Object
ConnectAndInitService - Requesting connection to Organization with Dataverse Version: No organization data available
Added WebClient Header Hooks to the Request object.
ConnectAndInitService - Proxy created, total elapsed time: 00:00:00.2624449
Querying Organization Instance Details. Request ID: 198cc1df-2372-4b25-bd0d-e45f08f74ef4
Execute Command - RetrieveCurrentOrganizationRequest : RequestId=00:00:00.0010680
Failed to Executed Command - RetrieveCurrentOrganizationRequest : RequestId=198cc1df-2372-4b25-bd0d-e45f08f74ef4 : total duration: 00:00:00.6612683
Source: Not Provided
Method: Not Provided
DateUTC: 07/12/2021
TimeUTC: 9.46.42
Error: Failed to Executed Command - RetrieveCurrentOrganizationRequest : RequestId=198cc1df-2372-4b25-bd0d-e45f08f74ef4 : total duration: 00:00:00.6612683
HelpLink Url: Not Provided
Stack Trace: Not Provided
======================================================================================================================

************ Exception - Failed to lookup current organization information
Source: System.Private.ServiceModel
Method: ValidateAuthentication
DateUTC: 07/12/2021
TimeUTC: 9.46.42
Error: The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was ''.
HelpLink Url: Not Provided
Stack Trace: at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateAuthentication()
   at System.ServiceModel.Channels.HttpResponseMessageHelper.ParseIncomingResponse(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.ReceiveReplyAsync(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.RequestAsyncInternal(Message message, TimeSpan timeout)
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
   at generatedProxy_1.Execute(OrganizationRequest )
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClientAsync.<>c__DisplayClass52_0.<ExecuteCore>b__0()
   at Microsoft.Xrm.Sdk.WebServiceClient.WebProxyClient`1.ExecuteAction[TResult](Func`1 action)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClientAsync.ExecuteCore(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClientAsync.Execute(OrganizationRequest request)
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.RefreshInstanceDetails(IOrganizationService dvService, Uri uriOfInstance)
======================================================================================================================

************ Exception - Fault While initializing client - RefreshInstanceDetails
==DataverseOperationException Info=======================================================================================
Source: Microsoft.PowerPlatform.Dataverse.Client
Error: Exception - Failed to lookup current organization data
ErrorCode: -2146233088
DateUTC: 07/12/2021
TimeUTC: 9.46.42
HelpLink Url: Not Provided
======================================================================================================================
Inner Exception Level 1 :
Source: System.Private.ServiceModel
Method: ValidateAuthentication
DateUTC: 07/12/2021
TimeUTC: 9.46.42
Error: The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was ''.
HelpLink Url: Not Provided
Stack Trace: at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateAuthentication()
   at System.ServiceModel.Channels.HttpResponseMessageHelper.ParseIncomingResponse(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.ReceiveReplyAsync(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.RequestAsyncInternal(Message message, TimeSpan timeout)
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
   at generatedProxy_1.Execute(OrganizationRequest )
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClientAsync.<>c__DisplayClass52_0.<ExecuteCore>b__0()
   at Microsoft.Xrm.Sdk.WebServiceClient.WebProxyClient`1.ExecuteAction[TResult](Func`1 action)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClientAsync.ExecuteCore(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClientAsync.Execute(OrganizationRequest request)
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.RefreshInstanceDetails(IOrganizationService dvService, Uri uriOfInstance)
======================================================================================================================

Unable to connect to Dataverse: Exception - Failed to lookup current organization data
Source: Microsoft.PowerPlatform.Dataverse.Client
Method: MoveNext
DateUTC: 07/12/2021
TimeUTC: 9.46.42
Error: Exception - Fault While initializing client - RefreshInstanceDetails
HelpLink Url: Not Provided
Stack Trace: at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.RefreshInstanceDetails(IOrganizationService dvService, Uri uriOfInstance)
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.DoDirectLoginAsync()
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.InitServiceAsync()
======================================================================================================================
Inner Exception Level 1 :
==DataverseOperationException Info=======================================================================================
Source: Microsoft.PowerPlatform.Dataverse.Client
Error: Exception - Failed to lookup current organization data
ErrorCode: -2146233088
DateUTC: 07/12/2021
TimeUTC: 9.46.42
HelpLink Url: Not Provided
======================================================================================================================
Inner Exception Level 2 :
Source: System.Private.ServiceModel
Method: ValidateAuthentication
DateUTC: 07/12/2021
TimeUTC: 9.46.42
Error: The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was ''.
HelpLink Url: Not Provided
Stack Trace: at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateAuthentication()
   at System.ServiceModel.Channels.HttpResponseMessageHelper.ParseIncomingResponse(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.ReceiveReplyAsync(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.RequestAsyncInternal(Message message, TimeSpan timeout)
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
   at generatedProxy_1.Execute(OrganizationRequest )
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClientAsync.<>c__DisplayClass52_0.<ExecuteCore>b__0()
   at Microsoft.Xrm.Sdk.WebServiceClient.WebProxyClient`1.ExecuteAction[TResult](Func`1 action)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClientAsync.ExecuteCore(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClientAsync.Execute(OrganizationRequest request)
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.RefreshInstanceDetails(IOrganizationService dvService, Uri uriOfInstance)
======================================================================================================================

Unhandled exception. Microsoft.PowerPlatform.Dataverse.Client.Utils.DataverseConnectionException: Failed to connect to Dataverse
 ---> System.AggregateException: One or more errors occurred. (Exception - Fault While initializing client - RefreshInstanceDetails)
 ---> Microsoft.PowerPlatform.Dataverse.Client.Utils.DataverseConnectionException: Exception - Fault While initializing client - RefreshInstanceDetails
 ---> Microsoft.PowerPlatform.Dataverse.Client.Utils.DataverseOperationException: Exception - Failed to lookup current organization data
 ---> System.ServiceModel.Security.MessageSecurityException: The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was ''.
   at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateAuthentication()
   at System.ServiceModel.Channels.HttpResponseMessageHelper.ParseIncomingResponse(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.ReceiveReplyAsync(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.RequestAsyncInternal(Message message, TimeSpan timeout)
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
   at generatedProxy_1.Execute(OrganizationRequest )
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClientAsync.<>c__DisplayClass52_0.<ExecuteCore>b__0()
   at Microsoft.Xrm.Sdk.WebServiceClient.WebProxyClient`1.ExecuteAction[TResult](Func`1 action)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClientAsync.ExecuteCore(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClientAsync.Execute(OrganizationRequest request)
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.RefreshInstanceDetails(IOrganizationService dvService, Uri uriOfInstance)
   --- End of inner exception stack trace ---
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.RefreshInstanceDetails(IOrganizationService dvService, Uri uriOfInstance)
   --- End of inner exception stack trace ---
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.InitServiceAsync()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.GetCachedService(ConnectionService& ConnectionObject)
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.IntilizeService(ConnectionService& ConnectionObject)
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.DoLogin(ConnectionService& ConnectionObject)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.CreateServiceConnection(Object externalOrgServiceProxy, AuthenticationType requestedAuthType, String hostName, String port, String orgName, NetworkCredential creden
tial, String userId, SecureString password, String domain, String Geo, String claimsHomeRealm, Boolean useSsl, Boolean useUniqueInstance, OrganizationDetail orgDetail, String clientId, Uri redirectUri, PromptBehavior promptBe
havior, OrganizationWebProxyClientAsync externalOrgWebProxyClient, String certificateThumbPrint, StoreName certificateStoreName, X509Certificate2 certificate, Uri instanceUrl, Boolean isCloned, Boolean useDefaultCreds, Versio
n incomingOrgVersion, ILogger externalLogger, String tokenCacheStorePath)
   --- End of inner exception stack trace ---
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.CreateServiceConnection(Object externalOrgServiceProxy, AuthenticationType requestedAuthType, String hostName, String port, String orgName, NetworkCredential creden
tial, String userId, SecureString password, String domain, String Geo, String claimsHomeRealm, Boolean useSsl, Boolean useUniqueInstance, OrganizationDetail orgDetail, String clientId, Uri redirectUri, PromptBehavior promptBe
havior, OrganizationWebProxyClientAsync externalOrgWebProxyClient, String certificateThumbPrint, StoreName certificateStoreName, X509Certificate2 certificate, Uri instanceUrl, Boolean isCloned, Boolean useDefaultCreds, Versio
n incomingOrgVersion, ILogger externalLogger, String tokenCacheStorePath)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient..ctor(Uri instanceUrl, Func`2 tokenProviderFunction, Boolean useUniqueInstance, ILogger logger)
   at Program.<Main>$(String[] args) in C:\src\foo\bar\Program.cs:line 48
   at Program.<Main>(String[] args)
```

**Comment by MattB-msft** [comment]
Will discuss with the team on this.
  
The code is returning the base URL for conciseness, as its assumed anytime this would be used it was for either online or IFD (OnPrem) related purposes.

**Comment by RedsGT** [comment]
Indeed, the setup documentation for onprem OAuth is designed around IFD and is technically the only supported scenario, as it's the documented one. https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/deploy/post-installation-configuration-guidelines-dynamics-365?view=op-9-1#configure-windows-server-for-dynamics-365-customer-engagement-on-premises-applications-that-use-oauth

**Comment by MattB-msft** [comment]
@bjorkstromm 
Sorry about the long pause in getting back to you, Lots of vacations and such over the Holidays. 

We did some deeper looking at this and determined that the ServiceClient is doing the "right thing" there based on the supported protocols for onPrem. 

In the case where JWT tokens are used, IFD Must be enabled, which requires the org name to appear in the <orgname>.<domain> form which is what the client is sending to the auth flow handler.  

The AD only flows which support <Hostname>\<orgname> do not accept JWT Tokens.  AD Auth flows are Kerberos or WS-TRUST only.

Could you tell me what your use case is for processing custom Auth via an AD configured instance? 

thanks

**Comment by MattB-msft** [comment]
Closing... Please reopen if you can provide more info
