### ISSUE TITLE
The path is empty. (Parameter 'path') when creating ServiceClient - publishing to single file

### ISSUE THREAD

**Issue by stonekw** [microsoft/PowerPlatform-DataverseServiceClient#215]
I have a self-contained .NET 5 console application that creates a ServiceClient with connection string. It worked when debugging, but wouldn't work when I published the exe to a folder and ran the exe. I unchecked "Produce single file" in the publishing settings, and the issue was resolved. I assume the issue has something to do with an assembly internal to Microsoft.PowerPlatform.Dataverse.Client, but not sure.

Here is the caught exception:
Failed to connect to Dataverse 
    at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.CreateServiceConnection(Object externalOrgServiceProxy, AuthenticationType requestedAuthType, String hostName, String port, String orgName, NetworkCredential credential, String userId, SecureString password, String domain, String Geo, String claimsHomeRealm, Boolean useSsl, Boolean useUniqueInstance, OrganizationDetail orgDetail, String clientId, Uri redirectUri, PromptBehavior promptBehavior, OrganizationWebProxyClientAsync externalOrgWebProxyClient, String certificateThumbPrint, StoreName certificateStoreName, X509Certificate2 certificate, Uri instanceUrl, Boolean isCloned, Boolean useDefaultCreds, Version incomingOrgVersion, ILogger externalLogger, String tokenCacheStorePath)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.ConnectToService(String connectionString, ILogger logger)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient..ctor(String dataverseConnectionString, ILogger logger)
   at deploy_windows_os.Program.ValidatePrerequisites()
   at deploy_windows_os.Program.Initialize(String[] args)
   at deploy_windows_os.Program.Main(String[] args) 
Inner Exception (if available): 
 One or more errors occurred. (The path is empty. (Parameter 'path')) 

This is the screenshot of the publishing settings that did not work. Unchecking "Produce single file" resolved the issue: 

![image](https://user-images.githubusercontent.com/16467359/145284290-d74665e9-4fe0-4fe9-b035-b5b3f13c1db0.png)

**Comment by MattB-msft** [comment]
thanks for your report, we are taking a look,
are you passing the connection string in to the client via cmdline? or are you reading it ( Hard coded or otherwise ) from within the client?

**Comment by MattB-msft** [comment]
Please retest this with the 0.6.6 release

**Comment by MattB-msft** [comment]
Going to close this at this point due to no response and the prospective fix in 0.6.6

**Comment by johnyenter-briars** [comment]
For anyone coming back to this thread, I had the exact same issue as @stonekw. Upgrading my nuget package to the latest: `1.0.1` at the time of writing has fixed the issue.

**Comment by stonekw** [comment]
I finally got back to this and retested with 1.0.26 and it is indeed resolved. Thanks for the help!
