### ISSUE TITLE
Error in ConnectionService.Command_WebExecuteAsync after SaveChanges

### ISSUE THREAD

**Issue by johandynamics** [microsoft/PowerPlatform-DataverseServiceClient#258]
Hi,

So we've been having issues where we get errors when connecting to Dynamics and creating an order.
We do three things, create an account, create the order and create the orderproducts. 

And we can't find a pattern but it can crash at any of these steps. And the same order is then retried and will be created but as a new one.

The error we find in our logs are the following:
```
Microsoft.Xrm.Sdk.SaveChangesException: An error occured while processing this request. ---> 
System.AggregateException: One or more errors occurred. 
(Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Uri'.) ---> 
System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Uri'. 
at System.Net.Http.Headers.HttpResponseHeaders.get_Location() 
at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.Command_WebAPIProcess_ExecuteAsync(OrganizationRequest req, String logMessageTag, Boolean bypassPluginExecution, MetadataUtility metadataUtlity, Guid callerId, Boolean disableConnectionLocking, Int32 maxRetryCount, TimeSpan retryPauseTime, CancellationToken cancellationToken, Uri uriOfInstance) 
--- End of inner exception stack trace --- 
at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.Execute(OrganizationRequest request) 
at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.Execute(OrganizationRequest request) 
at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.SaveChange(OrganizationRequest request, IList`1 results) 
--- End of inner exception stack trace --- 
at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.SaveChanges(SaveChangesOptions options) 
```
We think the error is the Command_WebAPIProcess_ExecuteAsync method that for some reason generates a list of Uri instead of a single one when HttpResponseHeaders.get_Location() is called.

We have gotten other errors too with the same method but other issues when looking at the exception:

```
Microsoft.Xrm.Sdk.SaveChangesException: An error occured while processing this request. ---> 
System.AggregateException: One or more errors occurred. (Collection was modified; enumeration operation may not execute.) --->
System.InvalidOperationException: Collection was modified; enumeration operation may not execute. 
at System.Collections.Generic.List`1.Enumerator.MoveNext() 
at System.Net.Http.Headers.HttpHeaders.ReadStoreValues[T](Span`1 values, Object storeValue, HttpHeaderParser parser, Int32& currentIndex) 
at System.Net.Http.Headers.HttpHeaders.GetStoreValuesAsStringOrStringArray(HeaderDescriptor descriptor, Object sourceValues, String& singleValue, String[]& multiValue)
at System.Net.Http.Headers.HttpHeaders.GetEnumeratorCore()+MoveNext() 
at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found) 
at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.Command_WebExecuteAsync(String queryString, String body, HttpMethod method, Dictionary`2 customHeaders, String contentType, String errorStringCheck, Guid callerId, Boolean disableConnectionLocking, Int32 maxRetryCount, TimeSpan retryPauseTime, Uri uriOfInstance, Guid requestTrackingId, CancellationToken cancellationToken) 
at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.Command_WebAPIProcess_ExecuteAsync(OrganizationRequest req, String logMessageTag, Boolean bypassPluginExecution, MetadataUtility metadataUtlity, Guid callerId, Boolean disableConnectionLocking, Int32 maxRetryCount, TimeSpan retryPauseTime, CancellationToken cancellationToken, Uri uriOfInstance) 
--- End of inner exception stack trace --- 
at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.Execute(OrganizationRequest request) 
at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.Execute(OrganizationRequest request) 
at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.SaveChange(OrganizationRequest request, IList`1 results) 
--- End of inner exception stack trace ---
 at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.SaveChanges(SaveChangesOptions options) 
```

And we have gotten this when creating a lead.

```
Microsoft.Xrm.Sdk.SaveChangesException: An error occured while processing this request. ---> 
System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.) ---> 
System.IndexOutOfRangeException: Index was outside the bounds of the array. 
at System.Net.Http.Headers.HttpHeaders.ReadStoreValues[T](Span`1 values, Object storeValue, HttpHeaderParser parser, Int32& currentIndex) 
at System.Net.Http.Headers.HttpHeaders.GetStoreValuesAsStringOrStringArray(HeaderDescriptor descriptor, Object sourceValues, String& singleValue, String[]& multiValue) 

at System.Net.Http.Headers.HttpHeaders.GetEnumeratorCore()+MoveNext() 
at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found) 
at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.Command_WebExecuteAsync(String queryString, String body, HttpMethod method, Dictionary`2 customHeaders, String contentType, String errorStringCheck, Guid callerId, Boolean disableConnectionLocking, Int32 maxRetryCount, TimeSpan retryPauseTime, Uri uriOfInstance, Guid requestTrackingId, CancellationToken cancellationToken) 

at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.Command_WebAPIProcess_ExecuteAsync(OrganizationRequest req, String logMessageTag, Boolean bypassPluginExecution, MetadataUtility metadataUtlity, Guid callerId, Boolean disableConnectionLocking, Int32 maxRetryCount, TimeSpan retryPauseTime, CancellationToken cancellationToken, Uri uriOfInstance) 

--- End of inner exception stack trace --- 
at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.Execute(OrganizationRequest request) 
at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.Execute(OrganizationRequest request) 
at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.SaveChange(OrganizationRequest request, IList`1 results)
 --- End of inner exception stack trace --- 
at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.SaveChanges(SaveChangesOptions options) 
```

We did update to the latest version 0.6.1 but that hasn't helped the issue for us. 
We sent a ticket to Microsoft support but they asked us to raise an issue here, and hopefully it's not completely wrong.

I'm guessing you are missing a ton of information to look at this, but since I'm not sure what you would need I hope you can instead tell me and I'll make sure to get you that info when needed.

**Comment by MattB-msft** [comment]
Thanks @johandynamics ,  
We are taking a look at this... Could you provide a code sample of your use case so that we can properly replicate it?  its important if your setting Lookups or using alt keys. 

Also can you set the property Client.UseWebAPI = false to see if that resolves it for you? 

Thanks

**Comment by johandynamics** [comment]
Hi @MattB-msft,
Thanks for a fast response, we'll start with setting the property Client.UseWebApi = false to start with and see what happens after that, I'll keep you posted.

**Comment by MattB-msft** [comment]
@johandynamics 
Is this working for you now?  if so can you close this?

**Comment by johandynamics** [comment]
@MattB-msft yes, we haven't had an error since 4:th of april when we released the fix with settijng client.UseWebApi = false.
So that did fix it for us. Thanks for the help.
