### ISSUE TITLE
Failed to connect to Dataverse

### ISSUE THREAD

**Issue by MoranShusheng** [microsoft/PowerPlatform-DataverseServiceClient#264]
I got the organization service in the Azure Function, but recently  I reported an error: ex.message is Failed to connect to Dataverse.
Microsoft.PowerPlatform.Dataverse.Client version is 0.4.12.
I got detailed error information:
` [2022-04-13T13:09:44.223Z] FROMTRACE: Initialize Dataverse connection Started - AuthType: OAuth
[2022-04-13T13:09:44.227Z] FROMTRACE: Direct Login Process Started
[2022-04-13T13:09:44.227Z] FROMTRACE: Attempting to Connect to Uri https://rmsaisa.crm5.dynamics.com/XRMServices/2011/Organization.svc
[2022-04-13T13:09:44.240Z] FROMTRACE: DiscoveryServer indicated organization service location = https://rmsaisa.crm5.dynamics.com/XRMServices/2011/Organization.svc
[2022-04-13T13:09:44.240Z] FROMTRACE: Organization Service URI is = https://rmsaisa.crm5.dynamics.com/XRMServices/2011/Organization.svc
[2022-04-13T13:09:44.245Z] FROMTRACE: ConnectAndInitService - Initializing Organization Service Object
[2022-04-13T13:09:44.245Z] FROMTRACE: ConnectAndInitService - Requesting connection to Organization with Dataverse Version: No organization data available
[2022-04-13T13:09:44.711Z] FROMTRACE: AuthenticateService - found authority with name https://login.microsoftonline.com/8b69898f-0512-xxxx-xxxx-be92f222d528/
[2022-04-13T13:09:44.713Z] FROMTRACE: AuthenticateService - found resource with name https://xxxxx.crm5.dynamics.com/
[2022-04-13T13:09:45.766Z] FROMTRACE: ERROR REQUESTING TOKEN FROM THE AUTHENTICATION CONTEXT - USER intervention required
[2022-04-13T13:09:45.910Z] FROMTRACE: AuthenticateService - found authority with name https://login.microsoftonline.com/8b69898f-0512-xxxx-xxxx-be92f222d528/
[2022-04-13T13:09:45.915Z] FROMTRACE: AuthenticateService - found resource with name https://xxxxx.crm5.dynamics.com/
[2022-04-13T13:09:45.917Z] FROMTRACE: ObtainAccessToken - PROMPT - Behavior: Auto
[2022-04-13T13:09:45.932Z] FROMTRACE: ERROR REQUESTING Token FROM THE Authentication context - General ADAL Error
[2022-04-13T13:09:45.933Z] Source: Microsoft.Identity.Client
[2022-04-13T13:09:45.934Z] Method: UpdateRedirectUri
[2022-04-13T13:09:45.935Z] DateUTC: 13/4/2022
[2022-04-13T13:09:45.935Z] TimeUTC: 13:09:45
[2022-04-13T13:09:45.936Z] Error: Only loopback redirect uri is supported, but app://58145b91-0c36-4500-8554-080854f2ac97/ was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details
[2022-04-13T13:09:45.937Z] HelpLink Url: Not Provided
[2022-04-13T13:09:45.938Z] Stack Trace: at Microsoft.Identity.Client.Platforms.Shared.Desktop.OsBrowser.DefaultOsBrowserWebUi.UpdateRedirectUri(Uri redirectUri)
[2022-04-13T13:09:45.938Z]    at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync(IWebUI webUi, CancellationToken cancellationToken)
[2022-04-13T13:09:45.939Z]    at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync(CancellationToken cancellationToken)
[2022-04-13T13:09:45.941Z]    at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)
[2022-04-13T13:09:45.945Z]    at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
[2022-04-13T13:09:45.946Z]    at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
[2022-04-13T13:09:45.947Z]    at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenInteractiveParameters interactiveParameters, CancellationToken cancellationToken)
[2022-04-13T13:09:45.948Z]    at Microsoft.PowerPlatform.Dataverse.Client.Auth.AuthProcessor.ObtainAccessTokenAsync(IPublicClientApplication publicAppClient, List`1 scopes, IAccount account, PromptBehavior promptBehavior, ClientCredentials clientCredentials, Boolean useDefaultCreds, DataverseTraceLogger logSink)
[2022-04-13T13:09:45.949Z]    at Microsoft.PowerPlatform.Dataverse.Client.Auth.AuthProcessor.ExecuteAuthenticateServiceProcessAsync(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, String clientId, Uri redirectUri, PromptBehavior promptBehavior, Boolean isOnPrem, String authority, Object msalAuthClient, DataverseTraceLogger logSink, Boolean useDefaultCreds, SecureString clientSecret, Boolean addVersionInfoToUri, IAccount user)
[2022-04-13T13:09:45.950Z] ======================================================================================================================
[2022-04-13T13:09:45.951Z]
[2022-04-13T13:09:45.954Z] FROMTRACE: Unable to connect to Dataverse: Only loopback redirect uri is supported, but app://58145b91-0c36-4500-8554-080854f2ac97/ was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details
[2022-04-13T13:09:45.955Z]
[2022-04-13T13:09:46.195Z] Executed 'QueryStoreApplicaiton' (Failed, Id=7cfacf48-608c-40e9-850c-769e440887dd, Duration=5589ms)
[2022-04-13T13:09:46.196Z] System.Private.CoreLib: Exception while executing function: QueryStoreApplicaiton. Microsoft.PowerPlatform.Dataverse.Client: Failed to connect to Dataverse. System.Private.CoreLib: One or more errors occurred. (Only loopback redirect uri is supported, but app://58145b91-0c36-4500-8554-080854f2ac97/ was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details). Microsoft.Identity.Client: Only loopback redirect uri is supported, but app://58145b91-0c36-4500-8554-080854f2ac97/ was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details.`

**Comment by MattB-msft** [comment]
For the sample application id, under **.net** core,  you need to change the redirect URI to "http://localhost"
that will allow it to work. 

For a function you should ONLY be using Client Secret or Client Certificate flows,  User Password flows are highly dangerous on headless clients due to MFA. 

MattB

**Comment by MoranShusheng** [comment]
I think I may not have expressed more details. I use the connection string to instantiate ServiceClient Object to get the organization service。Code example：
`string connectionString= "AuthType=OAuth;Url=https://xxxxx.crm5.dynamics.com;AppId=51f81489-12ee-4a9e-aaae-a2591f45987d;RedirectUri=app://58145B91-0C36-4500-8554-080854F2AC97;Username=xxxxx@mi.com;Password=xxxxxxxx;RequireNewInstance=False;"
var organizationServiceitem = new ServiceClient(connectionString, log);`

Historically, organization services have been fetched normally. But recently it failed with the error message as above. May I ask why this can't be used to get the organization service using that connection string recently? 

This  is our production environment, not a sample application. Is it OK to modify the redirect uri to "http://localhost"?

**Comment by MattB-msft** [comment]
The issue is with that flow is that internally it's using a MSAL Public Client flow.  That flow is intended user interaction logins not headless flow.  It's a user interactive login flow. 

Thus, my statement about switching to a client secret flow which are intended for headless flows.  The Client Secret and Client Certificate flows are intended to be used by Non-User Interactive Flows

The ID you're using there 51f81489-12ee-4a9e-aaae-a2591f45987d is our Sample application identifier for native clients. You should move off it for production workloads and create your own.  

It is already configured with the redirect uri http://localhost, so your good for that.

**Comment by MattB-msft** [comment]
@MoranShusheng  If your good to go, could you mark this as resolved? 
thanks

**Comment by MoranShusheng** [comment]
Testing has shown that the problem is caused by an expired password, and the problem no longer occurs after resetting the password and setting it to never expire. Now I can still get the organization service via the connection string.

It turns out that the problem has nothing to do with the redirect uri.

why not print the error that the password has expired, but print the redirect uri related information？

it bothers me.

**Comment by MattB-msft** [comment]
One of the limitations of working with MSAL is that you have to work with the MSAL client which controls all of that interaction. 

This error: 
`
[2022-04-13T13:09:45.933Z] Source: Microsoft.Identity.Client [2022-04-13T13:09:45.934Z] Method: UpdateRedirectUri [2022-04-13T13:09:45.935Z] DateUTC: 13/4/2022 [2022-04-13T13:09:45.935Z] TimeUTC: 13:09:45 [2022-04-13T13:09:45.936Z] Error: Only loopback redirect uri is supported, but app://58145b91-0c36-4500-8554-080854f2ac97/ was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details
`
Was MSAL trying to run its pop a login window flow.   Because the redirect URI was invalid, it failed there (which system to use to pop the window) and didn't report the "User Interaction Required" error, which is how a Password or MFA required error surfaces. 

If the redirect was correct, and MSAL got though that code, it should have found the popup was suppressed by the 'never' flag and then returned the appropriate error AAD Error ("User Interaction required") 

We have consider just generally catching that sort of thing and trying to provide a more formal message, but frankly, all that we (the caller) know at that point is that a User Interaction is required.   ADAL.net did do that and we had processing code for it in the CrmServiceClient, however that feature set was dropped in MSAL
You could voice your concern on the MSAL git hub issues board to see if they could append the underlying error messages diving the need for a UX pop.
