### ISSUE TITLE
Unable to connect dataverse from azure function with Vnet enabled

### ISSUE THREAD

**Issue by prabhuselvams1** [microsoft/PowerPlatform-DataverseServiceClient#282]
I was able to run azure function locally without issue but when I host the function in azure function app with vnet I couldn’t connect/instantiate service client with error “no organization data available”, is this know issue?

**Comment by MattB-msft** [comment]
That sounds like a permissions issue.  I would check the account your using.  Also you can enable logging and see what the client is saying during the connection process.

**Comment by prabhuselvams1** [comment]
Thanks Matt for the response. I'm using client id and secret to connect Dataverse, it does have access to Dataverse.
I'm able to run fun app locally and connect to same org without issue. Here is the detailed error message.

**Azure Function App Config and D365 connection details** 

Azure Function app has VNet enabled, so all outbound traffic b/w Azure Function and D365 goes via VNet.
Runtime version v3
Framework - .Net Core
Microsoft.PowerPlatform.Dataverse.client 
AuthType used clientsecret

**Error Details**
 

2022-06-08T13:35:56.753 [Information] Executing 'SitecoreToD365' (Reason='This function was programmatically called via the host APIs.', Id=febdd1fa-2616-4816-85b3-46fa9eaacf41)

2022-06-08T13:35:56.754 [Information] C# HTTP trigger function processed a request.

2022-06-08T13:35:56.754 [Information] Connection To Dynamic

2022-06-08T13:35:56.755 [Information] Attempting to Connect to Uri [https://xxx.crm.dynamics.com/XRMServices/2011/Organization.svc](https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fxxx.crm.dynamics.com%2FXRMServices%2F2011%2FOrganization.svc&data=05%7C01%7Cprabhu.selvam%40hcl.com%7C7eb9972c202248ebc17c08da4d7729fe%7C189de737c93a4f5a8b686f4ca9941912%7C0%7C0%7C637907471446897518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JPOA8XHa%2FWVTvm3u9Q5uZ29XwDbmeZvhSoWAZQKCgyA%3D&reserved=0)

2022-06-08T13:35:56.755 [None] BuildOrgConnectUri CoreClass ()

2022-06-08T13:35:56.755 [None] BuildOrgConnectUri CoreClass ()

2022-06-08T13:35:56.755 [Information] Organization Service URI is 'https://xxx.crm.dynamics.com/XRMServices/2011/Organization.svc'

2022-06-08T13:35:56.755 [Information] ConnectAndInitService - Requesting connection to Organization with Dataverse Version: No organization data available

2022-06-08T13:35:56.895 [Error] Failed to get response from: [https://xxx.crm.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.47.7698](https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fxxx.crm.dynamics.com%2FXRMServices%2F2011%2FOrganization.svc%2Fweb%3FSDKClientVersion%3D9.2.47.7698&data=05%7C01%7Cprabhu.selvam%40hcl.com%7C7eb9972c202248ebc17c08da4d7729fe%7C189de737c93a4f5a8b686f4ca9941912%7C0%7C0%7C637907471446897518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OaGNNC6yEpxrRziXfSlEOSVII9FdY5FoXRn%2BHmASmUE%3D&reserved=0); error: The SSL connection could not be established, see inner exception.

Source: Not Provided

Method: Not Provided

DateUTC: 6/8/2022

TimeUTC: 1:35:56 PM

Error: Failed to get response from: [https://xxx.crm.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.47.7698](https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fxxx.crm.dynamics.com%2FXRMServices%2F2011%2FOrganization.svc%2Fweb%3FSDKClientVersion%3D9.2.47.7698&data=05%7C01%7Cprabhu.selvam%40hcl.com%7C7eb9972c202248ebc17c08da4d7729fe%7C189de737c93a4f5a8b686f4ca9941912%7C0%7C0%7C637907471446897518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OaGNNC6yEpxrRziXfSlEOSVII9FdY5FoXRn%2BHmASmUE%3D&reserved=0); error: The SSL connection could not be established, see inner exception.

HelpLink Url: Not Provided

Stack Trace: Not Provided

======================================================================================================================

 

System.Exception : Failed to get response from: [https://xxxx.crm.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.47.7698](https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fxxxx.crm.dynamics.com%2FXRMServices%2F2011%2FOrganization.svc%2Fweb%3FSDKClientVersion%3D9.2.47.7698&data=05%7C01%7Cprabhu.selvam%40hcl.com%7C7eb9972c202248ebc17c08da4d7729fe%7C189de737c93a4f5a8b686f4ca9941912%7C0%7C0%7C637907471446897518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X9G1bjeH5bMZsRE9s2G6GTvMtP%2FK3IMOfJQmnAEMCe4%3D&reserved=0); error: The SSL connection could not be established, see inner exception.

2022-06-08T13:35:56.959 [Error] ERROR REQUESTING Token FROM THE Authentication context

Source: Not Provided

Method: Not Provided

DateUTC: 6/8/2022

TimeUTC: 1:35:56 PM

Error: ERROR REQUESTING Token FROM THE Authentication context

HelpLink Url: Not Provided

Stack Trace: Not Provided

======================================================================================================================

 

System.Exception : ERROR REQUESTING Token FROM THE Authentication context

2022-06-08T13:35:56.989 [Error] Source: Microsoft.PowerPlatform.Dataverse.Client

Method: MoveNext

DateUTC: 6/8/2022

TimeUTC: 1:35:56 PM

Error: Need a non-empty authority (Parameter 'Authority')

HelpLink Url: Not Provided

Stack Trace: at Microsoft.PowerPlatform.Dataverse.Client.Auth.AuthProcessor.ExecuteAuthenticateServiceProcessAsync(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, String clientId, Uri redirectUri, PromptBehavior promptBehavior, Boolean isOnPrem, String authority, Object msalAuthClient, DataverseTraceLogger logSink, Boolean useDefaultCreds, SecureString clientSecret, Boolean addVersionInfoToUri, IAccount user, MemoryBackedTokenCache memoryBackedTokenCache, String tokenCacheStorePath)

======================================================================================================================

 

System.ArgumentNullException : Need a non-empty authority (Parameter 'Authority')

   at async Microsoft.PowerPlatform.Dataverse.Client.Auth.AuthProcessor.ExecuteAuthenticateServiceProcessAsync(Uri serviceUrl,ClientCredentials clientCredentials,X509Certificate2 userCert,String clientId,Uri redirectUri,PromptBehavior promptBehavior,Boolean isOnPrem,String authority,Object msalAuthClient,DataverseTraceLogger logSink,Boolean useDefaultCreds,SecureString clientSecret,Boolean addVersionInfoToUri,IAccount user,MemoryBackedTokenCache memoryBackedTokenCache,String tokenCacheStorePath)

2022-06-08T13:35:57.004 [Error] Unable to connect to Dataverse: Need a non-empty authority (Parameter 'Authority')

 

System.ArgumentNullException : Need a non-empty authority (Parameter 'Authority')

   at async Microsoft.PowerPlatform.Dataverse.Client.Auth.AuthProcessor.ExecuteAuthenticateServiceProcessAsync(Uri serviceUrl,ClientCredentials clientCredentials,X509Certificate2 userCert,String clientId,Uri redirectUri,PromptBehavior promptBehavior,Boolean isOnPrem,String authority,Object msalAuthClient,DataverseTraceLogger logSink,Boolean useDefaultCreds,SecureString clientSecret,Boolean addVersionInfoToUri,IAccount user,MemoryBackedTokenCache memoryBackedTokenCache,String tokenCacheStorePath)

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at async Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.ConnectAndInitServiceAsync(OrganizationDetail orgdata,Boolean IsOnPrem,Uri homeRealmUri)

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at async Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.DoDirectLoginAsync(Boolean IsOnPrem)

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at async Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.InitServiceAsync()

2022-06-08T13:35:57.015 [Information] Dynamic 365 connecting Error Message Failed to connect to Dataverse

2022-06-08T13:35:57.015 [Information] Executed 'SitecoreToD365' (Succeeded, Id=febdd1fa-2616-4816-85b3-46fa9eaacf41, Duration=288ms)

**Comment by MattB-msft** [comment]
Going to close this now based on no response @prabhuselvams1 if your still seeing issues, please reopen it with more info.
Thanks
