### ISSUE TITLE
OutOfMemoryException - RetrieveEntityChanges : Execute (RetrieveEntityChanges) request to Dataverse

### ISSUE THREAD

**Issue by anilvem2** [microsoft/PowerPlatform-DataverseServiceClient#349]
I am trying to execute "RetrieveEntityChanges" request for an entity (ex: Incident) and which has many columns and every time I fetch max 5K rows.

All of a sudden, I get below error. When I try for other entity which has about 9 million rows, it works fine.
Where as Incident is just about 500K rows, it fails intermittently with the below error. Any fix for this?
It happens mostly for entities where we have large data to fetch.

**OutOfMemoryException - RetrieveEntityChanges : Execute (RetrieveEntityChanges) request to Dataverse from IOrganizationService |=> Exception of type 'System.OutOfMemoryException' was thrown.**
Source: System.Private.ServiceModel
Method: AllocateByteArray
DateUTC: 1/27/2023
TimeUTC: 5:04:45 PM
Error: Exception of type 'System.OutOfMemoryException' was thrown.
HelpLink Url: Not Provided
Stack Trace: at System.Runtime.Fx.AllocateByteArray(Int32 size)
   at System.Runtime.InternalBufferManager.PooledBufferManager.TakeBuffer(Int32 bufferSize)
   at System.ServiceModel.Channels.BufferManager.WrappingBufferManager.TakeBuffer(Int32 bufferSize)
   at System.ServiceModel.Channels.MessageEncoder.BufferMessageStreamAsync(Stream stream, BufferManager bufferManager, Int32 maxBufferSize, CancellationToken cancellationToken)
   at System.ServiceModel.Channels.MessageEncoder.ReadMessageAsync(Stream stream, BufferManager bufferManager, Int32 maxBufferSize, String contentType, CancellationToken cancellationToken)
   at System.ServiceModel.Channels.HttpResponseMessageHelper.ReadChunkedBufferedMessageAsync(Task`1 inputStreamTask, TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.HttpResponseMessageHelper.ParseIncomingResponse(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.ReceiveReplyAsync(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.RequestAsyncInternal(Message message, TimeSpan timeout)
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
   at generatedProxy_1.Execute(OrganizationRequest )
   at Microsoft.PowerPlatform.Dataverse.Client.Connector.OrganizationWebProxyClientAsync.<>c__DisplayClass52_0.<ExecuteCore>b__0()
   at Microsoft.PowerPlatform.Dataverse.Client.Connector.WebProxyClientAsync`1.ExecuteAction[TResult](Func`1 action)
   at Microsoft.PowerPlatform.Dataverse.Client.Connector.OrganizationWebProxyClientAsync.ExecuteCore(OrganizationRequest request)
   at Microsoft.PowerPlatform.Dataverse.Client.Connector.OrganizationWebProxyClientAsync.Execute(OrganizationRequest request)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.Command_Execute(OrganizationRequest req, String errorStringCheck, Boolean bypassPluginExecution)

**Comment by MattB-msft** [comment]
The error is coming from the host process running out of memory to provide to the payload translator ( the API interface reading the wire ) 
 
I would suggest you reduce your batch size to a smaller population to reduce the memory requirements on the transfer. 
Or, you can provide more memory to the overall process.

**Comment by anilvem2** [comment]
Thanks Matt for the clarification.
