### ISSUE TITLE
Error reading JObject from JsonReader. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by chinhpham** [microsoft/PowerPlatform-DataverseServiceClient#96]
Hello team,

I am running a thread pool of many CdsServiceClient instances with a large number of read/write requests via Cds WebApi

After some time (normally about an hour), I got the below error. Then all the subsequent get/post requests all failed for the same error.

Input: (1) `HttpMethod.Get`, (2) `accounts?$select=cs_id,accountid&$filter=(cs_id eq 5508502)`, others: `default`

Stack trace:

```
System.AggregateException: One or more errors occurred. (Error reading JObject from JsonReader. Path '', line 0, position 0.)
---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.ShouldRetryWebAPI(Exception ex, Int32 retryCount, Boolean& isThrottlingRetry)
at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.CdsCommand_WebExecuteAsync(String queryString, String body, HttpMethod method, Dictionary`2 customHeaders, String contentType, String errorStringCheck, Guid requestTrackingId)
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.ExecuteCdsWebRequest(HttpMethod method, String queryString, String body, Dictionary`2 customHeaders, String contentType)
```
 
Original connection for cloned clients:

```
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Verbose: 16 : Initialize CDS connection Started - AuthType: ClientSecret
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Verbose: 16 : Direct Login Process Started
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Information: 8 : Attempting to Connect to Uri https://company-dev.crm.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Start: 256 : BuildOrgConnectUri CoreClass ()
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Verbose: 16 : DiscoveryServer indicated organization service location = https://company-dev.crm.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Stop: 512 : BuildOrgConnectUri CoreClass ()
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Information: 8 : Organization Service URI is = https://company-dev.crm.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Verbose: 16 : ConnectAndInitCdsOrgService - Initializing Organization Service Object
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Information: 8 : ConnectAndInitCdsOrgService - Requesting connection to Organization with CDS Version: No organization data available
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Information: 8 : AuthenticateService - found authority with name https://login.microsoftonline.com/07aad2e5-aaec-42ff-be14-8e7c7198ce8d/
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Information: 8 : AuthenticateService - found resource with name https://company-dev.crm.dynamics.com/
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Verbose: 16 : Initial ObtainAccessToken - Client Secret
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Verbose: 16 : Added WebClient Header Hooks to the Request object.
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Information: 8 : ConnectAndInitCdsOrgService - Proxy created, total elapsed time: 00:00:01.6749368
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Information: 8 : Querying Organization Instance Details. Request ID: 41a4c053-6853-499e-9aeb-a064b1c2f308
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Information: 8 : Completed Querying Organization Instance Details, total duration: 00:00:00.7030873
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Verbose: 16 : Completed Parsing Organization Instance Details
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Information: 8 : Connected to User Organization (company-dev version: 9.2.20123.153)
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Verbose: 16 : Direct Login Process Succeeded - duration 00:00:02.4017208
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Information: 8 : Beginning Validation of CDS Connection. RequestID: 716a38b4-9723-4f65-81b5-f46714e7b4d5
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Information: 8 : Executed Command - WhoAmIRequest : RequestId=716a38b4-9723-4f65-81b5-f46714e7b4d5 : total duration: 00:00:00.0341196
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Information: 8 : Validation of CDS Connection Complete, total duration: 00:00:00.0349050
Microsoft.PowerPlatform.Cds.Client.CdsServiceClient Verbose: 16 : New Batch Manager Created, Max #of Batches:50000, Max #of RequestsPerBatch:5000
``` 
 
--
Btw, please consider making this a static method:` public T GetDataByKeyFromResultsSet<T>(Dictionary<string, object> results, string key)`

**Comment by MattB-msft** [comment]
Which AUTH type? / client version,  and can you check with current client? ( the one we shipped yesteday 2/11 ) 

We will take a look at that method.

**Comment by chinhpham** [comment]
AUTH type: ClientSecret. The same issue also happened to .3.6-a. I was about to post it but the new version had already shipped. I am also happy to see the Object null reference exception which occurred a lot in previous version has gone.

**Comment by MattB-msft** [comment]
Update to thread.. 
We believe that https://github.com/microsoft/PowerPlatform-DataverseServiceClient/issues/102 and this issue are related...
