### ISSUE TITLE
CdsTraceLogger - Index was outside the bounds of the array

### ISSUE THREAD

**Issue by chinhpham** [microsoft/PowerPlatform-DataverseServiceClient#97]
Running multiple threads with transient instances from CdsServiceClient pool. Seems like once an issue happened to an instance, the others would be affected as well.

Inputs: (1) `HttpMethod.Get`, or `HttpMethod.Post`

Stack Trace:

```
System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.Append(String value)
   at Microsoft.PowerPlatform.Cds.Client.CdsTraceLogger.Log(String message, TraceEventType eventType, Exception exception)
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.CdsCommand_WebExecuteAsync(String queryString, String body, HttpMethod method, Dictionary`2 customHeaders, String contentType, String errorStringCheck, Guid requestTrackingId)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.ExecuteCdsWebRequest(HttpMethod method, String queryString, String body, Dictionary`2 customHeaders, String contentType)
```

**Comment by MattB-msft** [comment]
Can you provide more information about how you are running into this?   We are not replicate this at this time.

**Comment by chinhpham** [comment]
I might have turned off the thread-safe option on the CdsServiceClient settings. Not sure how the unit tests were done, but if it had only covered the above Log function for a single thread, then could it be a multiple-threads issue with the `base.LastError` StringBuilder?

**Comment by MattB-msft** [comment]
Should not be causing an issue there we added box's to support writing there in a thread safe manner.... will have a look though it may have been lost in the port as we have been doing a good deal of refactoring in the logger. 

Going to flag is as a bug for now till we investigate it.
